import{a as y,S as b,i as d}from"./assets/vendor-5f0e12e0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();async function m(l,o){const i="40817348-8cf9cc617061525653a12724b",a="https://pixabay.com/api/";try{return(await y.get(a,{params:{key:i,q:l,image_type:"photo",orientation:"horizontal",safesearch:!0,order:"popular",page:o,per_page:40}})).data.hits}catch(r){throw r}}document.addEventListener("DOMContentLoaded",function(){const l=document.getElementById("search-form"),o=document.querySelector(".gallery"),i=new b(".gallery a");let a=1,e="",r;l.addEventListener("submit",async function(t){if(t.preventDefault(),e=this.elements.searchQuery.value.trim(),!e){f("Please enter a search query");return}o.addEventListener("click",function(n){n.target.classList.contains("js-card-link")&&(n.preventDefault(),i.open())}),o.innerHTML="",r=new IntersectionObserver(c,{threshold:.2});try{const n=await m(e,a);n.length===0?h("Sorry, there are no images matching your search query. Please try again."):(u(n,o),i.refresh(),r.observe(o))}catch(n){console.error("Error fetching images:",n),f("An error occurred while fetching images. Please try again later.")}});function c(t){t[0].isIntersecting&&g()}async function g(){a+=1,r.disconnect();try{const t=await m(e,a);t.length>0&&(u(t,o),i.refresh(),r.observe(o))}catch(t){console.error("Error fetching more images:",t),f("An error occurred while fetching more images. Please try again later.")}}function u(t,n){const s=p({hits:t});n.innerHTML+=s}function p(t){const{hits:n}=t;return n.map(s=>`
        <a href="${s.largeImageURL}" class="card-link js-card-link">
          <div class="photo-card">
            <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" class="photo"/>
            <div class="info">
              <p class="info-item"><b>Likes:</b>${s.likes}</p>
              <p class="info-item"><b>Views:</b>${s.views}</p>
              <p class="info-item"><b>Comments:</b>${s.comments}</p>
              <p class="info-item"><b>Downloads:</b>${s.downloads}</p>
            </div>
          </div>
        </a>
      `).join("")}function f(t){d.error({title:"Error",message:t})}function h(t){d.info({title:"Info",message:t})}});
//# sourceMappingURL=commonHelpers.js.map
